name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Setup
        run: pnpm run pub:build

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run pub:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm run pub:release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  sync-develop:
    needs: release
    name: Sync develop with main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Merge main into develop
        run: |
          git config pull.rebase true
          git fetch origin main
          git pull origin main
          git push origin develop
